export enum PayloadType {
	PROTO_MESSAGE = 5,
	ERROR_RES = 50,
	HEARTBEAT_EVENT = 51,

	APP_AUTH_REQ = 2100,
	APP_AUTH_RES = 2101,
	ACCOUNT_AUTH_REQ = 2102,
	ACCOUNT_AUTH_RES = 2103,
	VERSION_REQ = 2104,
	VERSION_RES = 2105,
	NEW_ORDER_REQ = 2106,
	TRAILING_SL_CHANGED_EVENT = 2107,
	CANCEL_ORDER_REQ = 2108,
	AMEND_ORDER_REQ = 2109,
	AMEND_POSITION_SLTP_REQ = 2110,
	CLOSE_POSITION_REQ = 2111,
	ASSET_LIST_REQ = 2112,
	ASSET_LIST_RES = 2113,
	SYMBOLS_LIST_REQ = 2114,
	SYMBOLS_LIST_RES = 2115,
	SYMBOL_BY_ID_REQ = 2116,
	SYMBOL_BY_ID_RES = 2117,
	SYMBOLS_FOR_CONVERSION_REQ = 2118,
	SYMBOLS_FOR_CONVERSION_RES = 2119,
	SYMBOL_CHANGED_EVENT = 2120,
	TRADER_REQ = 2121,
	TRADER_RES = 2122,
	TRADER_UPDATED_EVENT = 2123,
	RECONCILE_REQ = 2124,
	RECONCILE_RES = 2125,
	EXECUTION_EVENT = 2126,
	SUBSCRIBE_SPOTS_REQ = 2127,
	SUBSCRIBE_SPOTS_RES = 2128,
	UNSUBSCRIBE_SPOTS_REQ = 2129,
	UNSUBSCRIBE_SPOTS_RES = 2130,
	SPOT_EVENT = 2131,
	ORDER_ERROR_EVENT = 2132,
	DEAL_LIST_REQ = 2133,
	DEAL_LIST_RES = 2134,
	SUBSCRIBE_LIVE_TRENDBAR_REQ = 2135,
	UNSUBSCRIBE_LIVE_TRENDBAR_REQ = 2136,
	GET_TRENDBARS_REQ = 2137,
	GET_TRENDBARS_RES = 2138,
	EXPECTED_MARGIN_REQ = 2139,
	EXPECTED_MARGIN_RES = 2140,
	MARGIN_CHANGED_EVENT = 2141,
	OA_ERROR_RES = 2142,
	CASH_FLOW_HISTORY_REQ = 2143,
	CASH_FLOW_HISTORY_RES = 2144,
	GET_TICK_DATA_REQ = 2145,
	GET_TICK_DATA_RES = 2146,
	ACCOUNTS_TOKEN_INVALIDATED_EVENT = 2147,
	CLIENT_DISCONNECT_EVENT = 2148,
	GET_ACCOUNTS_BY_TOKEN_REQ = 2149,
	GET_ACCOUNTS_BY_TOKEN_RES = 2150,
	GET_CTID_PROFILE_REQ = 2151,
	GET_CTID_PROFILE_RES = 2152,
	ASSET_CLASS_LIST_REQ = 2153,
	ASSET_CLASS_LIST_RES = 2154,
	DEPTH_EVENT = 2155,
	SUBSCRIBE_DEPTH_REQ = 2156,
	SUBSCRIBE_DEPTH_RES = 2157,
	UNSUBSCRIBE_DEPTH_REQ = 2158,
	UNSUBSCRIBE_DEPTH_RES = 2159,
	SYMBOL_CATEGORY_LIST_REQ = 2160,
	SYMBOL_CATEGORY_LIST_RES = 2161,
	ACCOUNT_LOGOUT_REQ = 2162,
	ACCOUNT_LOGOUT_RES = 2163,
	ACCOUNT_DISCONNECT_EVENT = 2164,
	SUBSCRIBE_LIVE_TRENDBAR_RES = 2165,
	UNSUBSCRIBE_LIVE_TRENDBAR_RES = 2166,
	MARGIN_CALL_LIST_REQ = 2167,
	MARGIN_CALL_LIST_RES = 2168,
	MARGIN_CALL_UPDATE_REQ = 2169,
	MARGIN_CALL_UPDATE_RES = 2170,
	MARGIN_CALL_UPDATE_EVENT = 2171,
	MARGIN_CALL_TRIGGER_EVENT = 2172,
	REFRESH_TOKEN_REQ = 2173,
	REFRESH_TOKEN_RES = 2174,
	ORDER_LIST_REQ = 2175,
	ORDER_LIST_RES = 2176,
	GET_DYNAMIC_LEVERAGE_REQ = 2177,
	GET_DYNAMIC_LEVERAGE_RES = 2178,
	DEAL_LIST_BY_POSITION_REQ = 2179,
	DEAL_LIST_BY_POSITION_RES = 2180,
	ORDER_DETAILS_REQ = 2181,
	ORDER_DETAILS_RES = 2182,
	ORDER_LIST_BY_POSITION_REQ = 2183,
	ORDER_LIST_BY_POSITION_RES = 2184,
	DEAL_OFFSET_LIST_REQ = 2185,
	DEAL_OFFSET_LIST_RES = 2186,
	GET_POSITION_UNREALIZED_PNL_REQ = 2187,
	GET_POSITION_UNREALIZED_PNL_RES = 2188,
}

export enum OrderType {
	MARKET = 1,
	LIMIT = 2,
	STOP = 3,
	STOP_LOSS_TAKE_PROFIT = 4,
	MARKET_RANGE = 5,
	STOP_LIMIT = 6,
}

export enum TradeSide {
	BUY = 1,
	SELL = 2,
}

export enum TimeInForce {
	GOOD_TILL_DATE = 1,
	GOOD_TILL_CANCEL = 2,
	IMMEDIATE_OR_CANCEL = 3,
	FILL_OR_KILL = 4,
	MARKET_ON_OPEN = 5,
}

export enum ExecutionType {
	ORDER_ACCEPTED = 2,
	ORDER_FILLED = 3,
	ORDER_REPLACED = 4,
	ORDER_CANCELLED = 5,
	ORDER_EXPIRED = 6,
	ORDER_REJECTED = 7,
	ORDER_CANCEL_REJECTED = 8,
	SWAP = 9,
	DEPOSIT_WITHDRAW = 10,
	ORDER_PARTIAL_FILL = 11,
	BONUS_DEPOSIT_WITHDRAW = 12,
}

export enum PositionStatus {
	OPEN = 1,
	CLOSED = 2,
	CREATED = 3,
	ERROR = 4,
}

export enum OrderStatus {
	ACCEPTED = 1,
	FILLED = 2,
	REJECTED = 3,
	EXPIRED = 4,
	CANCELLED = 5,
}

export enum DealStatus {
	FILLED = 2,
	PARTIALLY_FILLED = 3,
	REJECTED = 4,
	INTERNALLY_REJECTED = 5,
	ERROR = 6,
	MISSED = 7,
}

export enum TrendbarPeriod {
	M1 = 1,
	M2 = 2,
	M3 = 3,
	M4 = 4,
	M5 = 5,
	M10 = 6,
	M15 = 7,
	M30 = 8,
	H1 = 9,
	H4 = 10,
	H12 = 11,
	D1 = 12,
	W1 = 13,
	MN1 = 14,
}

export enum QuoteType {
	BID = 1,
	ASK = 2,
}

export enum OrderTriggerMethod {
	TRADE = 1,
	OPPOSITE = 2,
	DOUBLE_TRADE = 3,
	DOUBLE_OPPOSITE = 4,
}

export enum DayOfWeek {
	NONE = 0,
	MONDAY = 1,
	TUESDAY = 2,
	WEDNESDAY = 3,
	THURSDAY = 4,
	FRIDAY = 5,
	SATURDAY = 6,
	SUNDAY = 7,
}

export enum CommissionType {
	USD_PER_MILLION_USD = 1,
	USD_PER_LOT = 2,
	PERCENTAGE_OF_VALUE = 3,
	QUOTE_CCY_PER_LOT = 4,
}

export enum SymbolDistanceType {
	SYMBOL_DISTANCE_IN_POINTS = 1,
	SYMBOL_DISTANCE_IN_PERCENTAGE = 2,
}

export enum MinCommissionType {
	CURRENCY = 1,
	QUOTE_CURRENCY = 2,
}

export enum TradingMode {
	ENABLED = 0,
	DISABLED_WITHOUT_PENDINGS_EXECUTION = 1,
	DISABLED_WITH_PENDINGS_EXECUTION = 2,
	CLOSE_ONLY_MODE = 3,
}

export enum SwapCalculationType {
	PIPS = 0,
	PERCENTAGE = 1,
	POINTS = 2,
}

export enum AccessRights {
	FULL_ACCESS = 0,
	CLOSE_ONLY = 1,
	NO_TRADING = 2,
	NO_LOGIN = 3,
}

export enum TotalMarginCalculationType {
	MAX = 0,
	SUM = 1,
	NET = 2,
}

export enum AccountType {
	HEDGED = 0,
	NETTED = 1,
	SPREAD_BETTING = 2,
}

export enum LimitedRiskMarginCalculationStrategy {
	ACCORDING_TO_LEVERAGE = 0,
	ACCORDING_TO_GSL = 1,
	ACCORDING_TO_GSL_AND_LEVERAGE = 2,
}

export enum StopOutStrategy {
	MOST_MARGIN_USED_FIRST = 0,
	MOST_LOSING_FIRST = 1,
}

export enum ClientPermissionScope {
	SCOPE_VIEW = 0,
	SCOPE_TRADE = 1,
}

export enum NotificationType {
	MARGIN_LEVEL_THRESHOLD_1 = 61,
	MARGIN_LEVEL_THRESHOLD_2 = 62,
	MARGIN_LEVEL_THRESHOLD_3 = 63,
}

export enum ChangeBonusType {
	BONUS_DEPOSIT = 0,
	BONUS_WITHDRAW = 1,
}

export enum ChangeBalanceType {
	BALANCE_DEPOSIT = 0,
	BALANCE_WITHDRAW = 1,
	BALANCE_DEPOSIT_STRATEGY_COMMISSION_INNER = 3,
	BALANCE_WITHDRAW_STRATEGY_COMMISSION_INNER = 4,
	BALANCE_DEPOSIT_IB_COMMISSIONS = 5,
	BALANCE_WITHDRAW_IB_SHARED_PERCENTAGE = 6,
	BALANCE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_SUB_IB = 7,
	BALANCE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_BROKER = 8,
	BALANCE_DEPOSIT_REBATE = 9,
	BALANCE_WITHDRAW_REBATE = 10,
	BALANCE_DEPOSIT_STRATEGY_COMMISSION_OUTER = 11,
	BALANCE_WITHDRAW_STRATEGY_COMMISSION_OUTER = 12,
	BALANCE_WITHDRAW_BONUS_COMPENSATION = 13,
	BALANCE_WITHDRAW_IB_SHARED_PERCENTAGE_TO_BROKER = 14,
	BALANCE_DEPOSIT_DIVIDENDS = 15,
	BALANCE_WITHDRAW_DIVIDENDS = 16,
	BALANCE_WITHDRAW_GSL_CHARGE = 17,
	BALANCE_WITHDRAW_ROLLOVER = 18,
	BALANCE_DEPOSIT_NONWITHDRAWABLE_BONUS = 19,
	BALANCE_WITHDRAW_NONWITHDRAWABLE_BONUS = 20,
	BALANCE_DEPOSIT_SWAP = 21,
	BALANCE_WITHDRAW_SWAP = 22,
	BALANCE_DEPOSIT_MANAGEMENT_FEE = 27,
	BALANCE_WITHDRAW_MANAGEMENT_FEE = 28,
	BALANCE_DEPOSIT_PERFORMANCE_FEE = 29,
	BALANCE_WITHDRAW_FOR_SUBACCOUNT = 30,
	BALANCE_DEPOSIT_TO_SUBACCOUNT = 31,
	BALANCE_WITHDRAW_FROM_SUBACCOUNT = 32,
	BALANCE_DEPOSIT_FROM_SUBACCOUNT = 33,
	BALANCE_WITHDRAW_COPY_FEE = 34,
	BALANCE_WITHDRAW_INACTIVITY_FEE = 35,
	BALANCE_DEPOSIT_TRANSFER = 36,
	BALANCE_WITHDRAW_TRANSFER = 37,
	BALANCE_DEPOSIT_CONVERTED_BONUS = 38,
	BALANCE_DEPOSIT_NEGATIVE_BALANCE_PROTECTION = 39,
}

export enum ProtoErrorCode {
	UNKNOWN_ERROR = 1,
	UNSUPPORTED_MESSAGE = 2,
	INVALID_REQUEST = 3,
	TIMEOUT_ERROR = 5,
	ENTITY_NOT_FOUND = 6,
	CANT_ROUTE_REQUEST = 7,
	FRAME_TOO_LONG = 8,
	MARKET_CLOSED = 9,
	CONCURRENT_MODIFICATION = 10,
	BLOCKED_PAYLOAD_TYPE = 11,
}

export enum ProtoOAErrorCode {
	OA_AUTH_TOKEN_EXPIRED = 1,
	ACCOUNT_NOT_AUTHORIZED = 2,
	RET_NO_SUCH_LOGIN = 12,
	ALREADY_LOGGED_IN = 14,
	RET_ACCOUNT_DISABLED = 64,
	CONNECTIONS_LIMIT_EXCEEDED = 67,
	WORSE_GSL_NOT_ALLOWED = 68,
	SYMBOL_HAS_HOLIDAY = 69,
	CH_CLIENT_AUTH_FAILURE = 101,
	CH_CLIENT_NOT_AUTHENTICATED = 102,
	CH_CLIENT_ALREADY_AUTHENTICATED = 103,
	CH_ACCESS_TOKEN_INVALID = 104,
	CH_SERVER_NOT_REACHABLE = 105,
	CH_CTID_TRADER_ACCOUNT_NOT_FOUND = 106,
	CH_OA_CLIENT_NOT_FOUND = 107,
	REQUEST_FREQUENCY_EXCEEDED = 108,
	SERVER_IS_UNDER_MAINTENANCE = 109,
	CHANNEL_IS_BLOCKED = 110,
	NOT_SUBSCRIBED_TO_SPOTS = 112,
	ALREADY_SUBSCRIBED = 113,
	SYMBOL_NOT_FOUND = 114,
	UNKNOWN_SYMBOL = 115,
	INCORRECT_BOUNDARIES = 35,
	NO_QUOTES = 117,
	NOT_ENOUGH_MONEY = 118,
	MAX_EXPOSURE_REACHED = 119,
	POSITION_NOT_FOUND = 120,
	ORDER_NOT_FOUND = 121,
	POSITION_NOT_OPEN = 122,
	POSITION_LOCKED = 123,
	TOO_MANY_POSITIONS = 124,
	TRADING_BAD_VOLUME = 125,
	TRADING_BAD_STOPS = 126,
	TRADING_BAD_PRICES = 127,
	TRADING_BAD_STAKE = 128,
	PROTECTION_IS_TOO_CLOSE_TO_MARKET = 129,
	TRADING_BAD_EXPIRATION_DATE = 130,
	PENDING_EXECUTION = 131,
	TRADING_DISABLED = 132,
	TRADING_NOT_ALLOWED = 133,
	UNABLE_TO_CANCEL_ORDER = 134,
	UNABLE_TO_AMEND_ORDER = 135,
	SHORT_SELLING_NOT_ALLOWED = 136,
}
